name: flutter_plugin_elui
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^1.5.4
  cached_network_image: ^2.1.0
  image_picker: ^0.6.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cabbagelol.flutter_elui_plugin
        pluginClass: FlutterEluiPlugin
      ios:
        pluginClass: FlutterEluiPlugin
